### ISSUE TITLE
Incorrect CNAME warning for beanstalk worker environments 

### ISSUE THREAD

**Issue by slatemine** [RiotGames/cinq-collector-aws#3]
Beanstalk worker environments are designed to consume messages from an SQS queue using an task local daemon which then sends the message to the API endpoint on localhost. 

I don't think worker environments have an EndpointURL. There role is to do background work so that the web environment can focus on just servicing request.
 
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts-worker.html

The warning line 362 of region.py should probably also check the whether it is looking at a `Web` or `Worker` environment.

**Comment by TheM0ng00se** [comment]
Hey @slatemine . Had a look at this and you're right that it's likely only appropriate for the WebServer tier not the worker tier. The beanstalk collector at the moment is only used for subdomain takeover, but could trigger false/unneeded warnings for beanstalk worker environments. 

We should probably rewrite to check for ['CNAME'] present and ['Tier']['Name'] = 'WebServer' which would satisfy this:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk-environment-tier.html

**Comment by bunjiboys** [comment]
This was fixed by https://github.com/RiotGames/cinq-collector-aws/pull/9 on March 8th, apologies for the lack of updates on the issue.
